version: "3.9"

services:
#  1. weather-app (Frontend/Entry Point - Client)
#  weather-app:
#    image: weather-client:latest
#    build:
#      context: ./client
#      dockerfile: Dockerfile
#    container_name: weather-app-container
#    ports:
#      - "3000:3000"  # host:container (Next.js runs on 3000 inside)
#    depends_on:
#      - weather-cache
#    environment:
#      - NODE_ENV=production
#      - NEXT_TELEMETRY_DISABLED=1
#    restart: unless-stopped

  # 2. weather-cache (Spring Boot App with Caching Logic)
  weather-cache:
    image: weather-cache:latest
    build:
      context: ./server/weather-cache
      dockerfile: Dockerfile
    container_name: weather-cache-container
    ports:
      - "8081:8081"
    # Ensure this .env file contains: REDIS_HOST=redis-db and the password/username
    env_file:
      - ./server/weather-cache/.env
    restart: unless-stopped
    depends_on:
      - weather-svc
      - redis-db

  # 3. weather-svc (Backend API Service)
  weather-svc:
    image: weather-svc:latest
    build:
      context: ./server/weather-svc
      dockerfile: Dockerfile
    container_name: weather-svc-container
    ports:
      - "8080:8080"
    env_file:
      - ./server/weather-svc/.env
    restart: unless-stopped

  # ===============================================
  # 4. redis-db (Local Redis Cache Instance)
  # ===============================================
  redis-db:
    image: redis:7.2.5-alpine
    container_name: redis-db-container
    ports:
      - "6379:6379"
    env_file:
      - ./server/weather-svc/.env
    volumes:
      - redis-data:/data
    restart: unless-stopped
    # 🔑 CRITICAL FIX: Configures Redis server to use the exact password from your .env file
    # The command enables AOF persistence and sets the required password.
    # command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes

# ===============================================
# TOP LEVEL VOLUMES
# ===============================================
volumes:
  redis-data:
