apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: dev
  labels:
    io.kompose.service: redis-data
    environment: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
