apiVersion: v1
kind: Service
metadata:
  name: weather-cache
spec:
  selector:
    app: weather-cache
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP  # internal load balancing