apiVersion: v1
kind: 
metadata:
  name: weather-app
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: weather-app
    environment: NAMESPACE_PLACEHOLDER
spec:
  type: LoadBalancer
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  