apiVersion: v1
kind: Service
metadata:
  name: weather-svc
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: weather-svc
    environment: NAMESPACE_PLACEHOLDER
spec:
  selector:
    app: weather-svc
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP