apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-cache
  labels:
    app: weather-cache
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-cache
  template:
    metadata:
      labels:
        app: weather-cache
    spec:
      containers:
        - name: weather-cache
          image: docker.io/shivamnamdeo0101/weather-cache:latest
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: server-weather-cache--env
      restartPolicy: Always

