apiVersion: v1
kind: Service
metadata:
  name: weather-cache
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: weather-cache
    environment: NAMESPACE_PLACEHOLDER
spec:
  type: LoadBalancer
  selector:
    app: weather-cache
  ports:
    - port: 8081
      targetPort: 8081
